create table usuarios (data_atualizacao timestamp(6) with time zone, data_criacao timestamp(6) with time zone not null, id bigint generated by default as identity, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, cpf varchar(255) not null unique, estado varchar(255) not null, logradouro varchar(255) not null, nome varchar(255) not null, primary key (id));

Popular a base de dados (Opcional):
```sql
INSERT INTO usuarios (id, nome, cpf, data_criacao, data_atualizacao, cep, logradouro, bairro, cidade, estado) VALUES
(1, 'João da Silva', '12345678901', now(), now(), '01001000', 'Praça da Sé', 'Sé', 'São Paulo', 'SP'),
(2, 'Maria Souza', '98765432100', now(), now(), '04003000', 'Rua Domingos de Morais', 'Vila Mariana', 'São Paulo', 'SP'),
(3, 'Carlos Pereira', '11122233344', now(), now(), '20040002', 'Rua Primeiro de Março', 'Centro', 'Rio de Janeiro', 'RJ'),
(4, 'Ana Lima', '22233344455', now(), now(), '30140071', 'Avenida Afonso Pena', 'Centro', 'Belo Horizonte', 'MG'),
(5, 'Pedro Santos', '33344455566', now(), now(), '40010000', 'Rua Chile', 'Centro', 'Salvador', 'BA'),
(6, 'Juliana Alves', '44455566677', now(), now(), '70040900', 'Esplanada dos Ministérios', 'Zona Cívico-Administrativa', 'Brasília', 'DF'),
(7, 'Lucas Martins', '55566677788', now(), now(), '80010000', 'Rua XV de Novembro', 'Centro', 'Curitiba', 'PR'),
(8, 'Fernanda Costa', '66677788899', now(), now(), '90010000', 'Rua dos Andradas', 'Centro Histórico', 'Porto Alegre', 'RS'),
(9, 'Rafael Oliveira', '77788899900', now(), now(), '60010000', 'Rua Barão de Studart', 'Centro', 'Fortaleza', 'CE'),
(10, 'Mariana Rocha', '88899900011', now(), now(), '80020180', 'Rua 24 de Maio', 'Centro', 'Curitiba', 'PR'),
(11, 'Eduardo Lima', '99900011122', now(), now(), '13010000', 'Avenida Carlos Botelho', 'Centro', 'Campinas', 'SP'),
(12, 'Patrícia Mendes', '10101010101', now(), now(), '70040000', 'Setor Comercial Sul', 'Plano Piloto', 'Brasília', 'DF'),
(13, 'Bruno Ferreira', '12121212121', now(), now(), '30130130', 'Rua da Bahia', 'Centro', 'Belo Horizonte', 'MG'),
(14, 'Carla Dias', '13131313131', now(), now(), '40020140', 'Rua das Laranjeiras', 'Campo Grande', 'Salvador', 'BA'),
(15, 'Thiago Santos', '14141414141', now(), now(), '20020150', 'Avenida Rio Branco', 'Centro', 'Rio de Janeiro', 'RJ'),
(16, 'Renata Gomes', '15151515151', now(), now(), '80030160', 'Avenida Sete de Setembro', 'Centro', 'Curitiba', 'PR'),
(17, 'Fábio Souza', '16161616161', now(), now(), '90030170', 'Rua Siqueira Campos', 'Centro Histórico', 'Porto Alegre', 'RS'),
(18, 'Vanessa Rocha', '17171717171', now(), now(), '60030180', 'Avenida Beira Mar', 'Meireles', 'Fortaleza', 'CE'),
(19, 'Gustavo Alves', '18181818181', now(), now(), '13020190', 'Rua Barreto Leme', 'Cambuí', 'Campinas', 'SP'),
(20, 'Isabela Martins', '19191919191', now(), now(), '70050100', 'Setor Militar Urbano', 'Plano Piloto', 'Brasília', 'DF');
```